Repository Michael-Tu/cppGFS2.0, pull requests merged in 2020-05, with the labels that each got.

#2 [refactor] add more directory structures
  src/protos/grpc/.gitkeep
  src/server/chunk_server/.gitkeep
  src/server/master_server/.gitkeep
  src/third_party/.gitkeep
  tests/server/chunk_server/.gitkeep
  tests/server/master_server/.gitkeep
Labels: enhancement

#12 [feat] add master metadata service gRPC proto definitions
  .travis.yml
  WORKSPACE
  src/protos/.gitkeep
  src/protos/BUILD.bazel
  src/protos/grpc/.gitkeep
  src/protos/grpc/BUILD.bazel
  src/protos/grpc/master_metadata_service.proto
  src/protos/metadata.proto
Labels: enhancement

#13 [fix] simplify gRPC for create and open
  src/protos/grpc/master_metadata_service.proto
Labels: fix

#14 [feat] Bring LevelDB into our codebase
  WORKSPACE
  examples/BUILD.bazel
  examples/leveldb_main.cc
  src/third_party/build_rules/BUILD.bazel
  src/third_party/build_rules/leveldb.BUILD
Labels: enhancement

#15 [feature]: Chunk server manager v1
  .travis.yml
  src/protos/BUILD.bazel
  src/protos/chunk_server.proto
  src/protos/grpc/BUILD.bazel
  src/protos/grpc/master_metadata_service.proto
  src/protos/metadata.proto
  src/server/master_server/BUILD.bazel
  src/server/master_server/chunk_server_manager.cc
  src/server/master_server/chunk_server_manager.h
  tests/server/master_server/BUILD.bazel
  tests/server/master_server/chunk_server_manager_test.cc
Labels: enhancement

#19 [style] readability fix for lock manager
  src/server/master_server/BUILD.bazel
  src/server/master_server/lock_manager.cc
  src/server/master_server/lock_manager.h
  tests/server/master_server/lock_manager_unit_test.cc
Labels: refactor

#16 [feat] Protocol manager for master metadata service, with basic server/client runner
  examples/BUILD.bazel
  examples/run_mock_client_main.cc
  src/common/.gitkeep
  src/common/BUILD.bazel
  src/common/protocol_client/BUILD.bazel
  src/common/protocol_client/master_metadata_service_client.cc
  src/common/protocol_client/master_metadata_service_client.h
  src/common/utils.cc
  src/common/utils.h
  src/server/master_server/.gitkeep
  src/server/master_server/BUILD.bazel
  src/server/master_server/master_metadata_service_impl.cc
  src/server/master_server/master_metadata_service_impl.h
  src/server/master_server/run_master_server_main.cc
Labels: enhancement

#20 [feat] chunk server gRPC protocol definitions
  src/protos/grpc/BUILD.bazel
  src/protos/grpc/chunk_server_file_service.proto
  src/protos/grpc/chunk_server_lease_service.proto
Labels: enhancement

#23 [feat] bring parallel hashmap to codebase
  WORKSPACE
  examples/BUILD.bazel
  examples/parallel_hashmap_main.cc
  src/third_party/build_rules/parallel_hashmap.BUILD
Labels: enhancement

#22 [feat] - System log manager v1
  WORKSPACE
  examples/BUILD.bazel
  examples/system_logger_main.cc
  src/common/BUILD.bazel
  src/common/system_logger.cc
  src/common/system_logger.h
  src/server/master_server/BUILD.bazel
  src/server/master_server/run_master_server_main.cc
Labels: enhancement

#27 [bug] make glog failure signal handler disabled by default, due to deadlock bug
  src/common/system_logger.cc
  src/common/system_logger.h
Labels: bug

#28 [feat] - Master chunk server manager service v1
  src/common/protocol_client/BUILD.bazel
  src/common/protocol_client/master_chunk_server_manager_service_client.cc
  src/common/protocol_client/master_chunk_server_manager_service_client.h
  src/protos/chunk_server.proto
  src/protos/grpc/BUILD.bazel
  src/protos/grpc/master_chunk_server_manager_service.proto
  src/server/master_server/BUILD.bazel
  src/server/master_server/master_chunk_server_manager_service_impl.cc
  src/server/master_server/master_chunk_server_manager_service_impl.h
  src/server/master_server/run_master_server_main.cc
Labels: enhancement

#25 [feat] more gRPC protocol clients and implementation placeholders
  examples/BUILD.bazel
  examples/run_mock_client_main.cc
  examples/run_mock_protocol_client_main.cc
  src/common/protocol_client/BUILD.bazel
  src/common/protocol_client/chunk_server_service_client.cc
  src/common/protocol_client/chunk_server_service_client.h
  src/common/protocol_client/master_metadata_service_client.cc
  src/common/utils.h
  src/server/chunk_server/BUILD.bazel
  src/server/chunk_server/chunk_server_file_service_impl.cc
  src/server/chunk_server/chunk_server_file_service_impl.h
  src/server/chunk_server/chunk_server_lease_service_impl.cc
  src/server/chunk_server/chunk_server_lease_service_impl.h
  src/server/chunk_server/run_chunk_server_main.cc
  src/server/master_server/master_metadata_service_impl.cc
  src/server/master_server/master_metadata_service_impl.h
Labels: enhancement

#29 Make chunk version a part of AdvanceFileChunkVersionRequest
  src/protos/grpc/chunk_server_file_service.proto
Labels: bug

#30 [feat] Add configuration manager v1
  WORKSPACE
  data/BUILD.bazel
  data/config.yml
  examples/BUILD.bazel
  examples/config_manager_main.cc
  src/common/BUILD.bazel
  src/common/config_manager.cc
  src/common/config_manager.h
  src/common/protocol_client/BUILD.bazel
  src/common/utils.cc
  src/common/utils.h
  src/third_party/build_rules/yaml_cpp.BUILD
  tests/common/BUILD.bazel
  tests/common/config_manager_test.cc
  tests/common/test_config.yml
Labels: enhancement

#32 [feat] Add CacheManager for client to manage metadata caching etc.
  src/client/BUILD.bazel
  src/client/client_cache_manager.cc
  src/client/client_cache_manager.h
  src/client/gfs_client.cc
  src/client/gfs_client.h
  tests/BUILD.bazel
  tests/client/BUILD.bazel
  tests/client/client_cache_manager_unit_test.cc
  tests/server/master_server/BUILD.bazel
  tests/server/master_server/lock_manager_unit_test.cc
  tests/server/master_server/metadata_manager_unit_test.cc
  tests/utils.cc
  tests/utils.h
Labels: enhancement

#36 Docker files with preliminary integration of protocol clients in master
  Dockerfile
  README.md
  docker-compose.yml
  examples/run_mock_protocol_client_main.cc
  src/server/chunk_server/run_chunk_server_main.cc
  src/server/master_server/BUILD.bazel
  src/server/master_server/lock_manager.cc
  src/server/master_server/lock_manager.h
  src/server/master_server/master_metadata_service_impl.cc
  src/server/master_server/master_metadata_service_impl.h
  src/server/master_server/run_master_server_main.cc
Labels: enhancement

#37 [feat] - Complete chunkserver manager and its services, and chunkserver control service for heartbeat
  src/common/protocol_client/BUILD.bazel
  src/common/protocol_client/chunk_server_control_service_client.cc
  src/common/protocol_client/chunk_server_control_service_client.h
  src/common/protocol_client/master_chunk_server_manager_service_client.cc
  src/common/protocol_client/master_chunk_server_manager_service_client.h
  src/common/utils.h
  src/protos/chunk_server.proto
  src/protos/grpc/BUILD.bazel
  src/protos/grpc/chunk_server_control_service.proto
  src/protos/grpc/master_chunk_server_manager_service.proto
  src/server/chunk_server/BUILD.bazel
  src/server/chunk_server/chunk_server_control_service_impl.cc
  src/server/chunk_server/chunk_server_control_service_impl.h
  src/server/master_server/BUILD.bazel
  src/server/master_server/chunk_server_manager.cc
  src/server/master_server/chunk_server_manager.h
  src/server/master_server/master_chunk_server_manager_service_impl.cc
  src/server/master_server/master_chunk_server_manager_service_impl.h
  tests/server/master_server/chunk_server_manager_test.cc
Labels: enhancement

#40 [feat] - File chunk manager
  src/protos/chunk_server.proto
  src/protos/grpc/BUILD.bazel
  src/protos/grpc/master_chunk_server_manager_service.proto
  src/server/chunk_server/BUILD.bazel
  src/server/chunk_server/file_chunk_manager.cc
  src/server/chunk_server/file_chunk_manager.h
  src/server/chunk_server/run_chunk_server_main.cc
  tests/server/chunk_server/BUILD.bazel
  tests/server/chunk_server/file_chunk_manager_test.cc
Labels: enhancement

#43 Fix all kinds of bugs in file chunk manager test
  src/server/chunk_server/file_chunk_manager.cc
  src/third_party/build_rules/leveldb.BUILD
  tests/server/chunk_server/file_chunk_manager_test.cc
Labels: bug

#42 [feat] Implement Chunk Server class, and lease RPC handler, with E2E test
  .travis.yml
  Dockerfile
  examples/run_mock_protocol_client_main.cc
  src/protos/grpc/chunk_server_lease_service.proto
  src/server/chunk_server/BUILD.bazel
  src/server/chunk_server/chunk_server_control_service_impl.h
  src/server/chunk_server/chunk_server_file_service_impl.h
  src/server/chunk_server/chunk_server_impl.cc
  src/server/chunk_server/chunk_server_impl.h
  src/server/chunk_server/chunk_server_lease_service_impl.cc
  src/server/chunk_server/chunk_server_lease_service_impl.h
  src/server/chunk_server/file_chunk_manager.h
  src/server/chunk_server/run_chunk_server_main.cc
  src/server/master_server/BUILD.bazel
  src/server/master_server/master_metadata_service_impl.cc
  src/server/master_server/master_metadata_service_impl.h
  src/server/master_server/run_master_server_main.cc
  tests/end_to_end/BUILD.bazel
  tests/end_to_end/file_creation_client.cc
  tests/server/chunk_server/BUILD.bazel
  tests/server/chunk_server/chunk_server_impl_test.cc
  tests/server/chunk_server/chunk_server_lease_impl_test.cc
  tests/server/chunk_server/test_config.yml
Labels: enhancement
